color industry
syntax on
set tabstop=2
set shiftwidth=0
set expandtab
set nu
sy enable
set list
set listchars=eol:$,nbsp:_,tab:>-,trail:~,extends:>,precedes:<
set rtp+=/usr/local/opt/fzf
set t_Co=256
