#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -pa /usr/local/fake_service/ebin debug verbose

-define(SCRIPT_NAME, app_controller).

-define(APP_NAME, fake_service).

main(["start"=_Arg]) ->
    try
	io:format("Application ~p is loading...~n", [?APP_NAME]),
	application:ensure_all_started(?APP_NAME)
    catch
	E:D ->
	    io:format("E:~p; D:~p~n ", [E,D]),
	    usage()
    end;
main(["stop"=_Arg]) ->
    io:format("stopping me~n~n", []),
    application:stop(?APP_NAME),
    application:unload(?APP_NAME);
main(_) ->
    usage().

usage() ->
    io:format("usage: ~p \"start\"|\"stop\"\n", [?SCRIPT_NAME]),
    halt(1).
