#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa /usr/local/fake_service/include/ /usr/local/fake_service/ebin/

-mode(compile).

-define(SCRIPT_NAME, app_controller).

-define(APP_NAME, fake_service).

main(["start"=_Arg]) ->
    try
	io:format("Application '~p' will be loaded and started~n", [?APP_NAME]),
	application:load(?APP_NAME),
	StartResult = application:start(?APP_NAME),
	io:format("Application `~p` has been loaded and started with status: ~p.~n", [?APP_NAME, StartResult])
    catch
	E:D ->
	    io:format("E:~p; D:~p~n ", [E,D]),
	    usage()
    end;
main(["stop"=_Arg]) ->
    io:format("stopping me"),
    application:stop(?APP_NAME),
    application:unload(?APP_NAME);
main(_) ->
    usage().

usage() ->
    io:format("usage: ~p \"start\"|\"stop\"\n", [?SCRIPT_NAME]),
    halt(1).
