#!/bin/sh
#
# PROVIDE: dummy
# REQUIRE:
# KEYWORD:

. /etc/rc.subr

name="oiz"
rcvar=${name}_enable

start_cmd="${name}_start"

_sleeptime=3 # seconds

oiz_start() {
    printf "Your daemon is starting ..."
    while true; do
		sleep $_sleeptime
		#python py.py
		start_poiz
    done 
}

load_rc_config ${name}

run_rc_command "$1"


